Missing package Dio and widget binding
zurichat/zc_desktop_flutter pull request #302
Opened 2021-09-03 11:11 UTC by Codesait

Added Missing package dio: ^4.0.0
Fixed shared pref get instance issue by adding WidgetsFlutterBinding.ensureInitialized();

2021-09-03 11:59 UTC, toxic-bishop approved these changes
LGTM

2021-09-03 13:59 UTC, developerjamiu requested changes
LGTM

2021-09-03 13:59 UTC, developerjamiu approved these changes

2021-09-04 01:20 UTC, toxic-bishop approved these changes
LGTM

2021-09-04 12:02 UTC, osobotu approved these changes
LGTM

2021-09-04 12:02 UTC, merged