Threads view UI
zurichat/zc_desktop_flutter pull request #564
Opened 2021-10-26 13:26 UTC by devRaphe

Implementation of the threads view, it is currently running on dummy data.
![threadsView](https://user-images.githubusercontent.com/72768624/138888238-c78a2977-b60c-4a10-bf55-5827ce330459.gif)

2021-10-26 15:40 UTC, Codesait requested changes
Please squash your commits

2021-10-26 16:19 UTC, ndungudedan submitted a review, later dismissed
LGTM

2021-10-27 01:12 UTC, Codesait approved these changes
LGTM

2021-10-27 07:43 UTC, PR073C7OR approved these changes
LGTM

2021-10-27 14:11 UTC, merged